### ISSUE TITLE
News page: Posts title will cater upto 2 lines only and post description line break tag is not observed.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Pace-Transport#11]
Conent <br/> line break tag not observed.

![untitled-1](https://cloud.githubusercontent.com/assets/13309730/11676229/85d42694-9e56-11e5-9d7d-5fedd3a58b20.png)

**Comment by ravi-josyula** [comment]
Still bug is not fixed
![2015-12-17_1207](https://cloud.githubusercontent.com/assets/13309806/11862980/fa1c8c32-a444-11e5-934a-9ebfc6fa9c53.png)
