### ISSUE TITLE
Pre-footer section: Pre Footer Title and Content will cater upto single line & two lines respectively.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Pace-Transport#16]
![pre-footer01](https://cloud.githubusercontent.com/assets/13309730/11676649/7ab340ac-9e5a-11e5-87d6-d09e77c83654.png)

**Comment by asif-titan** [comment]
As there is no link to a single page provided all the content should be shown for this section.

**Comment by mahender-sowedane** [comment]
Line space is not observed while testing, but working fine now
