### ISSUE TITLE
Lead-ins: Lead-thumb border is not implemented properly.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Pace-Transport#23]
![2015-12-09_1647](https://cloud.githubusercontent.com/assets/13309730/11684045/e371ac48-9e94-11e5-9c58-2460a8493a4f.png)

**Comment by asif-titan** [comment]
can you please explain the issue, every thing seems fine on my end.


![leadins](https://cloud.githubusercontent.com/assets/13450796/11848318/be77333c-a447-11e5-850e-d5d4c31339f7.png)

**Comment by mahender-sowedane** [comment]
While testing i found that issue but working fine now
and also overlay with border getting clipped and for home title line space is not observed
have a look this screen
thanks!
![untitled-1](https://cloud.githubusercontent.com/assets/13309730/11861514/2402c0fe-a4a7-11e5-8dcb-4c409ce4ec8c.png)
