### ISSUE TITLE
Transport Services page: Pagination is missing. If design does not have pagination, follow pagination styles from other pages.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Pace-Transport#31]
![2015-12-09_1734](https://cloud.githubusercontent.com/assets/13309730/11684931/30f8f6be-9e9b-11e5-8e88-d67834eac87b.png)

**Comment by asif-titan** [comment]
As per the design, all the posts are to be shown in a single page, that is why there is no pagination.
