### ISSUE TITLE
Transport Services page: Post title's should be one line only.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Pace-Transport#32]
![2015-12-09_1737](https://cloud.githubusercontent.com/assets/13309730/11684974/84a64258-9e9b-11e5-8e2e-959198d1d468.png)

**Comment by asif-titan** [comment]
As there is no single page for services and the whole content is shown on the listing page itself, the full title and content should be shown.

**Comment by mahender-sowedane** [comment]
And also line space is not observed, should be maintain atleast 1px gap between para lines
