### ISSUE TITLE
General pages: Unordered lists are not styled.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Pace-Transport#6]
![2015-12-07_2052](https://cloud.githubusercontent.com/assets/13309730/11630705/a18e7430-9d24-11e5-9689-b76488a8f360.png)

**Comment by ravi-josyula** [comment]
Still bug is not fixed, huge gape is occurring between ordered items and ordered items.
![2015-12-17_1224](https://cloud.githubusercontent.com/assets/13309806/11863287/8374617e-a447-11e5-8652-9eca20169ef4.png)

**Comment by asif-titan** [comment]
The space is due the margins of the second ordered list and the un-ordered list.
