### ISSUE TITLE
Lato Black: Is there another way to achieve the lato black from the design given? Currently it is not consistent, above lato black is font-weight: 900 and below lato black is font-weight: 700

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Pace-Transport#87]
![image](https://cloud.githubusercontent.com/assets/13363508/12254345/536f1b32-b922-11e5-8e74-f72d10099f6d.png)

**Comment by asif-titan** [comment]
As per the font designer the font weight for Lato Black is 900. so i think it will suffice if we just declare the font as LatoBlack with font-weight:normal.
