### ISSUE TITLE
Transport Services - Sidebar Right form: Submitting the form will receive the Post title from the Transport Services item post which supposedly not

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Pace-Transport#96]
![image](https://cloud.githubusercontent.com/assets/13363508/12407310/2c537380-be91-11e5-96fb-22df714ee588.png)

**Comment by maehtitan** [comment]
@asif-titan I did not filled up the Enquire button under each Transport Serivces custom post, it is the sidebar form I did test. Please understand the issue please

**Comment by asif-titan** [comment]
It is working fine on all the pages now except for the news page where it is showing the title of the latest post instead of the page title as it is a page for posts.

**Comment by ermatitan** [comment]
Not fix. Admin notification email for the field "Form sent form" should only display the page url where the form is submitted. Currently it also displays the page title and the URL.

![image](https://cloud.githubusercontent.com/assets/12791909/12438546/dc50aa60-bf62-11e5-9d99-1cf98c3060d9.png)
